version: "2.2"
services:
  jobmanager:
    image: flink:1.18.0-scala_2.12-java17
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
      - |
        FLAG=flag{i_can_takeover_your_cluster}

  taskmanager:
    image: flink:1.18.0-scala_2.12-java17
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
