services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8.8.20
    volumes:
      - ./clickhouse/config:/docker-entrypoint-initdb.d
    networks:
      - db
    healthcheck:
      test: clickhouse-client --query "select count(1) from system.tables"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./flag:/flag
    ports:
      - "1337:1337"
    networks:
      - db
      - external

networks:
  db:
    internal: true
  external:
    internal: false
