services:
  clickhouse:
    image: yandex/clickhouse-server:21.3.2.5
    volumes:
      - ./flag:/flag
    ports:
      - "8123:8123"
    healthcheck:
      test: clickhouse-client --query "select count(1) from system.tables"
